# Turn the vendored TTFs into a C++ translation unit, so cosmo's typeface travels INSIDE the
# binary (R-FONT-1): no font file beside the executable, no Fontconfig, no dependency on what the
# host happens to have installed — which is the only way the text is identical on every platform.
#
# Run as: cmake -DFONTS="<family>|<path>;<family>|<path>;..." -DOUT=<file.cpp> -P embed_fonts.cmake
#
# `file(READ ... HEX)` + one regex is the whole trick: it needs no external tool (no xxd, no
# objcopy, no host codegen target to build first), so it works the same on Linux and MSYS2, and
# `add_custom_command` reruns it only when a TTF actually changes.
if(NOT DEFINED FONTS OR NOT DEFINED OUT)
  message(FATAL_ERROR "embed_fonts.cmake needs -DFONTS=... and -DOUT=...")
endif()

set(body "")
set(table "")
set(index 0)
foreach(entry IN LISTS FONTS)
  string(REPLACE "|" ";" parts "${entry}")
  list(GET parts 0 family)
  list(GET parts 1 path)
  if(NOT EXISTS "${path}")
    message(FATAL_ERROR "embed_fonts: no such font file: ${path}")
  endif()
  file(READ "${path}" hex HEX)
  string(LENGTH "${hex}" hexlen)
  math(EXPR bytes "${hexlen} / 2")
  string(REGEX REPLACE "(..)" "0x\\1," data "${hex}")
  # Wrap so the generated file is not one line of several hundred thousand characters, which
  # some compilers and every diff tool handle badly.
  string(REGEX REPLACE "(0x..,0x..,0x..,0x..,0x..,0x..,0x..,0x..,0x..,0x..,0x..,0x..,)" "\\1\n"
         data "${data}")
  string(APPEND body "// ${family} — ${bytes} bytes\n")
  string(APPEND body "const unsigned char kFont${index}[] = {\n${data}\n};\n\n")
  string(APPEND table "    {\"${family}\", kFont${index}, ${bytes}},\n")
  math(EXPR index "${index} + 1")
endforeach()

file(WRITE "${OUT}" "// GENERATED by cmake/embed_fonts.cmake — do not edit, and do not commit.
// The faces cosmo draws with, compiled into the binary (R-FONT-1).
#include \"EmbeddedFonts.h\"

namespace arstro
{
namespace cosmo_v2
{
namespace
{
${body}}

const std::vector<EmbeddedFont> &embeddedFonts()
{
    // Static, so the bytes outlive every face FreeType builds from them — which is
    // CairoTarget::registerFontMemory's contract (Artboard FR-22a).
    static const std::vector<EmbeddedFont> kFonts = {
${table}    };
    return kFonts;
}
}
}
")
message(STATUS "embed_fonts: wrote ${index} faces to ${OUT}")
