/*
 *  interstellar_host_tests — the FFmpeg frame source against REAL containers (R-VOL, R-TL-5).
 *
 *  The timeline asks for "source frame N" and must get frame N, in any container a user brings:
 *  mp4, mov, mkv (H.264, HEVC 10-bit, VP9), 29.97 fps, and — the case that froze playback — a
 *  stream whose first timestamp is not zero (a camera, OBS or a stream recorder writes those).
 *  The media is generated by `tests/host_media.sh` with the ffmpeg binary; every file is
 *  testsrc2, which changes on every frame, so two consecutive frames must differ.
 *
 *  And the deep path (R-COLOR-1) end to end: a 16-bit ramp written to 10-bit ProRes by the real
 *  writer and read back by the real decoder keeps several times the levels an 8-bit one does.
 *
 *      interstellar_host_tests <file>…
 */
#ifdef NDEBUG
#undef NDEBUG
#endif
#include <cassert>

#include "FrameSourceFFmpeg.h"
#include "FrameWriterFFmpeg.h"
#include <cstdio>
#include <algorithm>
#include <set>
#include <utility>
#include <cstdint>
#include <string>
#include <vector>

using namespace arstro;

static uint64_t hashRaster(const interstellar::Raster &r)
{
    uint64_t h = 1469598103934665603ULL;
    for (uint8_t b : r.rgba) { h ^= b; h *= 1099511628211ULL; }
    return h;
}

int main(int argc, char **argv)
{
    std::setvbuf(stdout, nullptr, _IONBF, 0);
    assert(argc > 1);
    for (int a = 1; a < argc; ++a)
    {
        const std::string path = argv[a];
        interstellar_host::FrameSourceFFmpeg src;
        interstellar::IFrameSource::Info info;
        assert(src.open(path, info) && info.valid());
        // Four seconds of testsrc2 at whatever rate the file says.
        const long long expect = (long long)(4.0 * info.fps + 0.5);
        std::printf("%s: %dx%d %.3f fps, %lld frames (expect ~%lld)\n", path.c_str(), info.width, info.height,
                    info.fps, info.frames, expect);
        assert(info.frames >= expect - 2 && info.frames <= expect + 2);
        // R-UI-15: the source's own bit depth reaches the scopes' readout
        assert(info.bitDepth == (path.find("hevc10") != std::string::npos ? 10 : 8));

        // Sequential: every frame is a NEW picture — a frozen run is the playback bug.
        const long long n = std::min<long long>(info.frames, 72);
        std::vector<uint64_t> seq;
        interstellar::Raster r;
        for (long long f = 0; f < n; ++f)
        {
            assert(src.frameAt(f, r) && !r.empty());
            seq.push_back(hashRaster(r));
            if (f > 0 && seq[(size_t)f] == seq[(size_t)f - 1])
            {
                std::printf("  FROZEN: frame %lld repeats frame %lld\n", f, f - 1);
                assert(false);
            }
        }
        // Random access lands on the SAME frame sequential decoding produced (seek correctness).
        interstellar_host::FrameSourceFFmpeg again;
        interstellar::IFrameSource::Info i2;
        assert(again.open(path, i2));
        for (long long f : {n - 1, n / 2, (long long)3, n / 3, (long long)0})
        {
            assert(again.frameAt(f, r));
            if (hashRaster(r) != seq[(size_t)f])
            {
                std::printf("  SEEK MISS: frameAt(%lld) after a seek is not sequential frame %lld\n", f, f);
                assert(false);
            }
        }
        std::printf("  [PASS] %lld sequential frames distinct; 5 seeks land exactly\n", n);
    }

    // ── R-COLOR-1: a 10-bit file written deep holds more than 8 bits ──
    {
        const std::string first = argv[1];
        const std::string dir = first.find('/') == std::string::npos ? std::string(".") : first.substr(0, first.rfind('/'));
        const int W = 320, H = 180;
        interstellar::Raster ramp;   // 320 steps of 8/65535: ten 8-bit codes end to end
        ramp.allocate16(W, H, 65535);
        for (int y = 0; y < H; ++y)
            for (int x = 0; x < W; ++x)
            {
                uint16_t *p = &ramp.rgba16[((size_t)y * W + x) * 4];
                p[0] = p[1] = p[2] = (uint16_t)(30000 + x * 8);
            }
        interstellar::Raster ramp8;
        interstellar::toShallow(ramp, ramp8);
        auto writeAndCount = [&](const interstellar::Raster &frame, const std::string &name, bool readDeep) {
            interstellar::EncodeSpec spec;
            spec.codec = "prores";
            spec.profile = "standard";
            spec.bitDepth = 10;
            const std::string out = dir + "/" + name;
            {
                interstellar_host::FrameWriterFFmpeg w;
                assert(w.begin(out, W, H, 24.0, 2, spec));
                assert(w.write(frame) && w.write(frame) && w.end());
            }
            interstellar_host::FrameSourceFFmpeg src;
            interstellar::IFrameSource::Info info;
            assert(src.open(out, info) && info.bitDepth == 10);
            interstellar::Raster back;
            assert(readDeep ? src.frameAtDeep(0, back) : src.frameAt(0, back));
            assert(back.deep() == readDeep && back.width == W);
            // the levels along the middle row, and its longest flat run: a staircase has long ones
            std::set<int> levels;
            int run = 1, longest = 1, prev = -1;
            for (int x = 0; x < W; ++x)
            {
                const int v = readDeep ? back.rgba16[((size_t)90 * W + x) * 4] : back.rgba[((size_t)90 * W + x) * 4];
                levels.insert(v);
                run = v == prev ? run + 1 : 1;
                longest = std::max(longest, run);
                prev = v;
            }
            return std::make_pair((int)levels.size(), longest);
        };
        const auto deep = writeAndCount(ramp, "deep.mov", true);
        const auto fromEight = writeAndCount(ramp8, "eight.mov", true);   // 8-bit in: the file cannot gain bits
        const auto readEight = writeAndCount(ramp, "deep8.mov", false);   // and an 8-bit read of a deep file drops them
        std::printf("  10-bit ProRes round trip (levels / longest flat run of 320 px): deep %d/%d, from 8-bit %d/%d, read at 8-bit %d/%d\n",
                    deep.first, deep.second, fromEight.first, fromEight.second, readEight.first, readEight.second);
        // ten 8-bit codes over 320 px are 32-px steps; 10-bit levels are ~4x finer
        assert(deep.first >= 30 && deep.second <= 16);
        assert(fromEight.second >= 24 && readEight.second >= 24 && readEight.first <= 12);
        std::printf("  [PASS] a deep frame keeps its 10 bits through the real writer and decoder\n");
    }
    std::printf("interstellar_host_tests: %d file(s) passed\n", argc - 1);
    return 0;
}
