/*
 *  interstellar_host_tests — the FFmpeg frame source against REAL containers (R-VOL, R-TL-5).
 *
 *  The timeline asks for "source frame N" and must get frame N, in any container a user brings:
 *  mp4, mov, mkv (H.264, HEVC 10-bit, VP9), 29.97 fps, and — the case that froze playback — a
 *  stream whose first timestamp is not zero (a camera, OBS or a stream recorder writes those).
 *  The media is generated by `tests/host_media.sh` with the ffmpeg binary; every file is
 *  testsrc2, which changes on every frame, so two consecutive frames must differ.
 *
 *      interstellar_host_tests <file>…
 */
#ifdef NDEBUG
#undef NDEBUG
#endif
#include <cassert>

#include "FrameSourceFFmpeg.h"
#include <cstdio>
#include <cstdint>
#include <string>
#include <vector>

using namespace arstro;

static uint64_t hashRaster(const interstellar::Raster &r)
{
    uint64_t h = 1469598103934665603ULL;
    for (uint8_t b : r.rgba) { h ^= b; h *= 1099511628211ULL; }
    return h;
}

int main(int argc, char **argv)
{
    std::setvbuf(stdout, nullptr, _IONBF, 0);
    assert(argc > 1);
    for (int a = 1; a < argc; ++a)
    {
        const std::string path = argv[a];
        interstellar_host::FrameSourceFFmpeg src;
        interstellar::IFrameSource::Info info;
        assert(src.open(path, info) && info.valid());
        // Four seconds of testsrc2 at whatever rate the file says.
        const long long expect = (long long)(4.0 * info.fps + 0.5);
        std::printf("%s: %dx%d %.3f fps, %lld frames (expect ~%lld)\n", path.c_str(), info.width, info.height,
                    info.fps, info.frames, expect);
        assert(info.frames >= expect - 2 && info.frames <= expect + 2);
        // R-UI-15: the source's own bit depth reaches the scopes' readout
        assert(info.bitDepth == (path.find("hevc10") != std::string::npos ? 10 : 8));

        // Sequential: every frame is a NEW picture — a frozen run is the playback bug.
        const long long n = std::min<long long>(info.frames, 72);
        std::vector<uint64_t> seq;
        interstellar::Raster r;
        for (long long f = 0; f < n; ++f)
        {
            assert(src.frameAt(f, r) && !r.empty());
            seq.push_back(hashRaster(r));
            if (f > 0 && seq[(size_t)f] == seq[(size_t)f - 1])
            {
                std::printf("  FROZEN: frame %lld repeats frame %lld\n", f, f - 1);
                assert(false);
            }
        }
        // Random access lands on the SAME frame sequential decoding produced (seek correctness).
        interstellar_host::FrameSourceFFmpeg again;
        interstellar::IFrameSource::Info i2;
        assert(again.open(path, i2));
        for (long long f : {n - 1, n / 2, (long long)3, n / 3, (long long)0})
        {
            assert(again.frameAt(f, r));
            if (hashRaster(r) != seq[(size_t)f])
            {
                std::printf("  SEEK MISS: frameAt(%lld) after a seek is not sequential frame %lld\n", f, f);
                assert(false);
            }
        }
        std::printf("  [PASS] %lld sequential frames distinct; 5 seeks land exactly\n", n);
    }
    std::printf("interstellar_host_tests: %d file(s) passed\n", argc - 1);
    return 0;
}
