/*
 *  interstellar_host_tests — the FFmpeg frame source against REAL containers (R-VOL, R-TL-5).
 *
 *  The timeline asks for "source frame N" and must get frame N, in any container a user brings:
 *  mp4, mov, mkv (H.264, HEVC 10-bit, VP9), 29.97 fps, and — the case that froze playback — a
 *  stream whose first timestamp is not zero (a camera, OBS or a stream recorder writes those).
 *  The media is generated by `tests/host_media.sh` with the ffmpeg binary; every file is
 *  testsrc2, which changes on every frame, so two consecutive frames must differ.
 *
 *  And the deep path (R-COLOR-1) end to end: a 16-bit ramp written to 10-bit ProRes by the real
 *  writer and read back by the real decoder keeps several times the levels an 8-bit one does.
 *
 *      interstellar_host_tests <file>…
 */
#ifdef NDEBUG
#undef NDEBUG
#endif
#include <cassert>

#include "AudioSourceFFmpeg.h"
#include "DngWrite.h"
#include "FrameSourceFFmpeg.h"
#include "FrameWriterFFmpeg.h"
#include "PackageWriter.h"
#include <fstream>
#include <iterator>
extern "C" {
#include <libavcodec/avcodec.h>
#include <libavformat/avformat.h>
}
#include "HostFrameSource.h"
#include "Sequence.h"
#include "VideoFrameDecoder.h"
#include <filesystem>
#include <cstdio>
#include <algorithm>
#include <set>
#include <utility>
#include <cmath>
#include <cstdint>
#include <string>
#include <vector>

using namespace arstro;

static uint64_t hashRaster(const interstellar::Raster &r)
{
    uint64_t h = 1469598103934665603ULL;
    for (uint8_t b : r.rgba) { h ^= b; h *= 1099511628211ULL; }
    return h;
}

int main(int argc, char **argv)
{
    std::setvbuf(stdout, nullptr, _IONBF, 0);
    assert(argc > 1);
    for (int a = 1; a < argc; ++a)
    {
        const std::string path = argv[a];
        interstellar_host::FrameSourceFFmpeg src;
        interstellar::IFrameSource::Info info;
        assert(src.open(path, info) && info.valid());
        // Four seconds of testsrc2 at whatever rate the file says.
        const long long expect = (long long)(4.0 * info.fps + 0.5);
        std::printf("%s: %dx%d %.3f fps, %lld frames (expect ~%lld)\n", path.c_str(), info.width, info.height,
                    info.fps, info.frames, expect);
        assert(info.frames >= expect - 2 && info.frames <= expect + 2);
        // R-UI-15: the source's own bit depth reaches the scopes' readout
        assert(info.bitDepth == (path.find("hevc10") != std::string::npos ? 10 : 8));

        // Sequential: every frame is a NEW picture — a frozen run is the playback bug.
        const long long n = std::min<long long>(info.frames, 72);
        std::vector<uint64_t> seq;
        interstellar::Raster r;
        for (long long f = 0; f < n; ++f)
        {
            assert(src.frameAt(f, r) && !r.empty());
            seq.push_back(hashRaster(r));
            if (f > 0 && seq[(size_t)f] == seq[(size_t)f - 1])
            {
                std::printf("  FROZEN: frame %lld repeats frame %lld\n", f, f - 1);
                assert(false);
            }
        }
        // Random access lands on the SAME frame sequential decoding produced (seek correctness).
        interstellar_host::FrameSourceFFmpeg again;
        interstellar::IFrameSource::Info i2;
        assert(again.open(path, i2));
        for (long long f : {n - 1, n / 2, (long long)3, n / 3, (long long)0})
        {
            assert(again.frameAt(f, r));
            if (hashRaster(r) != seq[(size_t)f])
            {
                std::printf("  SEEK MISS: frameAt(%lld) after a seek is not sequential frame %lld\n", f, f);
                assert(false);
            }
        }
        std::printf("  [PASS] %lld sequential frames distinct; 5 seeks land exactly\n", n);
    }

    // ── R-COLOR-1: a 10-bit file written deep holds more than 8 bits ──
    {
        const std::string first = argv[1];
        const std::string dir = first.find('/') == std::string::npos ? std::string(".") : first.substr(0, first.rfind('/'));
        const int W = 320, H = 180;
        interstellar::Raster ramp;   // 320 steps of 8/65535: ten 8-bit codes end to end
        ramp.allocate16(W, H, 65535);
        for (int y = 0; y < H; ++y)
            for (int x = 0; x < W; ++x)
            {
                uint16_t *p = &ramp.rgba16[((size_t)y * W + x) * 4];
                p[0] = p[1] = p[2] = (uint16_t)(30000 + x * 8);
            }
        interstellar::Raster ramp8;
        interstellar::toShallow(ramp, ramp8);
        auto writeAndCount = [&](const interstellar::Raster &frame, const std::string &name, bool readDeep) {
            interstellar::EncodeSpec spec;
            spec.codec = "prores";
            spec.profile = "standard";
            spec.bitDepth = 10;
            const std::string out = dir + "/" + name;
            {
                interstellar_host::FrameWriterFFmpeg w;
                assert(w.begin(out, W, H, 24.0, 2, spec));
                assert(w.write(frame) && w.write(frame) && w.end());
            }
            interstellar_host::FrameSourceFFmpeg src;
            interstellar::IFrameSource::Info info;
            assert(src.open(out, info) && info.bitDepth == 10);
            interstellar::Raster back;
            assert(readDeep ? src.frameAtDeep(0, back) : src.frameAt(0, back));
            assert(back.deep() == readDeep && back.width == W);
            // the levels along the middle row, and its longest flat run: a staircase has long ones
            std::set<int> levels;
            int run = 1, longest = 1, prev = -1;
            for (int x = 0; x < W; ++x)
            {
                const int v = readDeep ? back.rgba16[((size_t)90 * W + x) * 4] : back.rgba[((size_t)90 * W + x) * 4];
                levels.insert(v);
                run = v == prev ? run + 1 : 1;
                longest = std::max(longest, run);
                prev = v;
            }
            return std::make_pair((int)levels.size(), longest);
        };
        const auto deep = writeAndCount(ramp, "deep.mov", true);
        const auto fromEight = writeAndCount(ramp8, "eight.mov", true);   // 8-bit in: the file cannot gain bits
        const auto readEight = writeAndCount(ramp, "deep8.mov", false);   // and an 8-bit read of a deep file drops them
        std::printf("  10-bit ProRes round trip (levels / longest flat run of 320 px): deep %d/%d, from 8-bit %d/%d, read at 8-bit %d/%d\n",
                    deep.first, deep.second, fromEight.first, fromEight.second, readEight.first, readEight.second);
        // ten 8-bit codes over 320 px are 32-px steps; 10-bit levels are ~4x finer
        assert(deep.first >= 30 && deep.second <= 16);
        assert(fromEight.second >= 24 && readEight.second >= 24 && readEight.first <= 12);
        std::printf("  [PASS] a deep frame keeps its 10 bits through the real writer and decoder\n");
    }
    // ── R-AUD-5 (amended): the decoder, and the writer's sound read back by it ──
    {
        const std::string first = argv[1];
        const std::string dir = first.find('/') == std::string::npos ? std::string(".") : first.substr(0, first.rfind('/'));
        auto measure = [](const std::vector<float> &st, int ch, double rate, double &peak, double &hz) {
            peak = 0;
            int zc = 0;
            const size_t n = st.size() / 2;
            for (size_t i = 0; i < n; ++i)
            {
                peak = std::max(peak, (double)std::fabs(st[i * 2 + ch]));
                if (i && (st[(i - 1) * 2 + ch] < 0) != (st[i * 2 + ch] < 0)) ++zc;
            }
            hz = zc / 2.0 / (n / rate);
        };
        interstellar_host::AudioSourceFFmpeg mono;
        interstellar::IAudioSource::Info info;
        assert(mono.open(dir + "/tone_mono.wav", 48000, info) && std::fabs(info.duration - 2.0) < 0.01 && info.fileRate == 44100 && info.fileChannels == 1);
        std::vector<float> buf(24000 * 2);
        assert(mono.read(24000, 24000, buf.data()));
        double peak = 0, hz = 0;
        measure(buf, 0, 48000, peak, hz);
        std::printf("  mono 1 kHz at 44.1 kHz, read at 48 kHz: peak %.4f, %.1f Hz\n", peak, hz);
        assert(std::fabs(peak - 0.125) < 0.003 && std::fabs(hz - 1000) < 3);
        for (size_t i = 0; i < 24000; ++i) assert(buf[i * 2] == buf[i * 2 + 1]);   // mono: the same in both ears, at its own level
        // a seek lands on the same samples as reading straight through to it
        interstellar_host::AudioSourceFFmpeg seq, jump;
        assert(seq.open(dir + "/tone_stereo.m4a", 48000, info) && jump.open(dir + "/tone_stereo.m4a", 48000, info));
        std::vector<float> a(4096 * 2), b(4096 * 2);
        for (long long p = 0; p < 60000; p += 4096) seq.read(p, 4096, a.data());
        seq.read(60000, 4096, a.data());
        jump.read(60000, 4096, b.data());
        double worst = 0;
        for (size_t i = 128; i < a.size(); ++i) worst = std::max(worst, (double)std::fabs(a[i] - b[i]));
        std::printf("  stereo AAC: a seek to frame 60000 vs reading through: worst %.5f\n", worst);
        assert(worst < 2e-3);
        std::vector<float> lr(24000 * 2);
        jump.read(24000, 24000, lr.data());
        double pl = 0, hl = 0, pr = 0, hr = 0;
        measure(lr, 0, 48000, pl, hl);
        measure(lr, 1, 48000, pr, hr);
        assert(std::fabs(hl - 440) < 3 && std::fabs(hr - 880) < 3);   // left is left, right is right
        // the writer: 2 s of picture with a 0.5-amplitude 1 kHz tone, in both of its audio codecs
        for (const char *codec : {"prores", "h264"})
        {
            interstellar::EncodeSpec spec;
            spec.codec = codec;
            spec.profile = std::string(codec) == "prores" ? "standard" : "";
            spec.bitDepth = std::string(codec) == "prores" ? 10 : 8;
            spec.audioRate = 48000;
            const std::string out = dir + "/sound." + (std::string(codec) == "prores" ? "mov" : "mp4");
            interstellar_host::FrameWriterFFmpeg w;
            assert(w.begin(out, 64, 36, 24.0, 48, spec));
            interstellar::Raster frame;
            frame.allocate(64, 36, 128);
            std::vector<float> tone(2000 * 2);
            for (int k = 0; k < 48; ++k)
            {
                for (int i = 0; i < 2000; ++i)
                    tone[i * 2] = tone[i * 2 + 1] = 0.5f * (float)std::sin(2 * 3.14159265358979 * 1000.0 * (k * 2000 + i) / 48000.0);
                assert(w.write(frame) && w.writeAudio(tone.data(), 2000));
            }
            assert(w.end());
            interstellar_host::AudioSourceFFmpeg back;
            assert(back.open(out, 48000, info) && std::fabs(info.duration - 2.0) < 0.05);
            std::vector<float> got(24000 * 2);
            back.read(24000, 24000, got.data());
            measure(got, 0, 48000, peak, hz);
            std::printf("  %s: the muxed tone reads back at peak %.4f, %.1f Hz, %.3f s\n", codec, peak, hz, info.duration);
            assert(std::fabs(peak - 0.5) < (std::string(codec) == "prores" ? 1e-4 : 0.02) && std::fabs(hz - 1000) < 3);
        }
        std::printf("  [PASS] audio: decoded at the mix rate, mono at unity, seeks exact, and the writer's sound reads back\n");
    }
    // ── R-DLV-1: a subtitle track — mov_text in an MP4, SubRip in an MKV — read back cue by cue ──
    {
        const std::string first = argv[1];
        const std::string dir = first.find('/') == std::string::npos ? std::string(".") : first.substr(0, first.rfind('/'));
        for (const char *ext : {"mp4", "mkv"})
        {
            interstellar::EncodeSpec spec;
            spec.subtitles = {{0.25, 0.75, "Hello\nworld"}, {1.0, 1.5, "Second"}};
            const std::string out = dir + "/captions." + ext;
            interstellar_host::FrameWriterFFmpeg w;
            assert(w.begin(out, 64, 36, 24.0, 48, spec));
            interstellar::Raster frame;
            frame.allocate(64, 36, 128);
            for (int k = 0; k < 48; ++k) assert(w.write(frame));
            assert(w.end());
            AVFormatContext *fmt = nullptr;
            assert(avformat_open_input(&fmt, out.c_str(), nullptr, nullptr) == 0 && avformat_find_stream_info(fmt, nullptr) >= 0);
            int si = -1;
            for (unsigned i = 0; i < fmt->nb_streams; ++i)
                if (fmt->streams[i]->codecpar->codec_type == AVMEDIA_TYPE_SUBTITLE) si = (int)i;
            assert(si >= 0 && fmt->streams[si]->codecpar->codec_id == (std::string(ext) == "mkv" ? AV_CODEC_ID_SUBRIP : AV_CODEC_ID_MOV_TEXT));
            std::vector<std::pair<double, std::string>> cues;
            AVPacket *pkt = av_packet_alloc();
            while (av_read_frame(fmt, pkt) >= 0)
            {
                if (pkt->stream_index == si && pkt->size > 2)
                {
                    // mov_text: a 16-bit length, then the UTF-8; SubRip: the text itself
                    const bool movText = fmt->streams[si]->codecpar->codec_id == AV_CODEC_ID_MOV_TEXT;
                    const int len = movText ? (pkt->data[0] << 8 | pkt->data[1]) : pkt->size;
                    const std::string text(reinterpret_cast<const char *>(pkt->data) + (movText ? 2 : 0), (size_t)len);
                    if (!text.empty()) cues.emplace_back(pkt->pts * av_q2d(fmt->streams[si]->time_base), text);
                }
                av_packet_unref(pkt);
            }
            av_packet_free(&pkt);
            avformat_close_input(&fmt);
            std::printf("  %s: %zu cues — %.3f s \"%s\", %.3f s \"%s\"\n", ext, cues.size(), cues.empty() ? 0.0 : cues[0].first,
                        cues.empty() ? "" : cues[0].second.c_str(), cues.size() < 2 ? 0.0 : cues[1].first, cues.size() < 2 ? "" : cues[1].second.c_str());
            assert(cues.size() == 2 && std::fabs(cues[0].first - 0.25) < 0.002 && std::fabs(cues[1].first - 1.0) < 0.002);
            assert(cues[0].second.find("Hello") == 0 && cues[0].second.find("world") != std::string::npos && cues[1].second == "Second");
        }
        {
            interstellar::EncodeSpec spec;
            spec.codec = "prores";
            spec.profile = "standard";
            spec.bitDepth = 10;
            spec.subtitles = {{0.0, 1.0, "x"}};
            interstellar_host::FrameWriterFFmpeg w;
            assert(w.begin(dir + "/captions.mov", 64, 36, 24.0, 24, spec));   // MOV carries mov_text too
            interstellar::Raster frame;
            frame.allocate(64, 36, 128);
            for (int k = 0; k < 24; ++k) assert(w.write(frame));
            assert(w.end());
        }
        std::printf("  [PASS] subtitles: mov_text in MP4 and MOV, SubRip in MKV, each cue at its time with its words\n");
    }
    // ── R-DLV-4: a DCP and an IMF package — MXF that FFmpeg reads back frame by frame, and XML that names it ──
    {
        const std::string first = argv[1];
        const std::string dir = first.find('/') == std::string::npos ? std::string(".") : first.substr(0, first.rfind('/'));
        auto slurp = [](const std::string &p) {
            std::ifstream f(p, std::ios::binary);
            return std::string((std::istreambuf_iterator<char>(f)), std::istreambuf_iterator<char>());
        };
        auto between = [](const std::string &s, const std::string &a, const std::string &b, size_t from = 0) {
            const size_t i = s.find(a, from);
            if (i == std::string::npos) return std::string();
            const size_t j = s.find(b, i + a.size());
            return j == std::string::npos ? std::string() : s.substr(i + a.size(), j - i - a.size());
        };
        for (const bool imf : {false, true})
        {
            const std::string pkg = dir + (imf ? "/pkg_imf" : "/pkg_dcp");
            std::filesystem::remove_all(pkg);
            interstellar::EncodeSpec spec;
            spec.codec = imf ? "imf" : "dcp";
            spec.bitDepth = 12;
            spec.audioRate = 48000;
            spec.output = imf ? "rec709" : "dcdm";
            const int w = 1920, h = 1080;
            if (!imf) { spec.containerW = 1998; spec.containerH = 1080; }   // 2K Flat: the picture pillarboxed
            interstellar_host::PackageWriter pw;
            assert(pw.begin(pkg, w, h, 24.0, 3, spec));
            assert(pw.note().find("NOT validated") != std::string::npos);
            interstellar::Raster frame;
            frame.allocate(w, h, 0);
            interstellar::toDeep(frame, frame);
            for (int y = 0; y < h; ++y)
                for (int x = 0; x < w; ++x)
                    for (int c = 0; c < 3; ++c) frame.rgba16[((size_t)y * w + x) * 4 + c] = (uint16_t)(x * 65535 / (w - 1));
            std::vector<float> tone(2000 * 2);
            for (int i = 0; i < 2000; ++i) tone[i * 2] = tone[i * 2 + 1] = 0.25f * (float)std::sin(2 * 3.14159265358979 * 1000.0 * i / 48000.0);
            for (int k = 0; k < 3; ++k) assert(pw.write(frame) && pw.writeAudio(tone.data(), 2000));
            if (!pw.end()) { std::printf("package: %s\n", pw.error().c_str()); assert(false); }
            // the track files: FFmpeg's MXF demuxer finds the JPEG 2000 stream, three frames, at the container's size
            std::string picFile, sndFile, cplFile, pklFile;
            for (const auto &e : std::filesystem::directory_iterator(pkg))
            {
                const std::string n = e.path().filename().string();
                if (n.rfind(imf ? "IMG_" : "j2c_", 0) == 0) picFile = e.path().string();
                if (n.rfind(imf ? "AUD_" : "pcm_", 0) == 0) sndFile = e.path().string();
                if (n.rfind(imf ? "CPL_" : "cpl_", 0) == 0) cplFile = e.path().string();
                if (n.rfind(imf ? "PKL_" : "pkl_", 0) == 0) pklFile = e.path().string();
            }
            assert(!picFile.empty() && !sndFile.empty() && !cplFile.empty() && !pklFile.empty());
            assert(std::filesystem::exists(pkg + "/ASSETMAP.xml") && std::filesystem::exists(pkg + "/VOLINDEX.xml") == !imf);
            AVFormatContext *fmt = nullptr;
            assert(avformat_open_input(&fmt, picFile.c_str(), nullptr, nullptr) == 0 && avformat_find_stream_info(fmt, nullptr) >= 0);
            assert(fmt->nb_streams >= 1 && fmt->streams[0]->codecpar->codec_id == AV_CODEC_ID_JPEG2000);
            assert(fmt->streams[0]->codecpar->width == (imf ? 1920 : 1998) && fmt->streams[0]->codecpar->height == 1080);
            int packets = 0;
            AVPacket *pkt = av_packet_alloc();
            while (av_read_frame(fmt, pkt) >= 0)
            {
                if (pkt->size > 2 && pkt->data[0] == 0xff && pkt->data[1] == 0x4f && packets++ == 0 && !imf)
                {
                    // the picture centred in 2K Flat: its brightest column (x 1919 of 1920) at 39 + 1919, black beyond
                    const AVCodec *dec = avcodec_find_decoder(AV_CODEC_ID_JPEG2000);
                    AVCodecContext *dc = avcodec_alloc_context3(dec);
                    AVFrame *fr = av_frame_alloc();
                    assert(avcodec_open2(dc, dec, nullptr) == 0 && avcodec_send_packet(dc, pkt) == 0 && avcodec_receive_frame(dc, fr) == 0);
                    auto px = [&](int x, int y, int c) { return (int)reinterpret_cast<const uint16_t *>(fr->data[0] + (size_t)y * fr->linesize[0])[x * 3 + c] >> 4; };
                    std::printf("  DCP frame: X'Y'Z' at x 1957 = %d %d %d, at x 1980 = %d\n", px(1957, 540, 0), px(1957, 540, 1), px(1957, 540, 2), px(1980, 540, 1));
                    assert(fr->format == AV_PIX_FMT_XYZ12LE && px(1957, 540, 1) > 3000 && px(1980, 540, 1) < 16 && px(10, 540, 1) < 16);
                    av_frame_free(&fr);
                    avcodec_free_context(&dc);
                }
                av_packet_unref(pkt);
            }
            av_packet_free(&pkt);
            avformat_close_input(&fmt);
            assert(packets == 3);
            {
                // the index names each frame's KLV (an essence key at every offset) and the header the duration —
                // both written at the end, the header rewritten in place
                const std::string mxf = slurp(picFile);
                const std::string jkey("\x06\x0e\x2b\x34\x01\x02\x01\x01\x0d\x01\x03\x01\x15\x01\x08\x01", 16);
                const std::string idxKey("\x06\x0e\x2b\x34\x02\x53\x01\x01\x0d\x01\x02\x01\x01\x10\x01\x00", 16);
                const std::string rgbaKey("\x06\x0e\x2b\x34\x02\x53\x01\x01\x0d\x01\x01\x01\x01\x01\x29\x00", 16);
                auto be = [&](size_t at, int n) { uint64_t v = 0; for (int i = 0; i < n; ++i) v = v << 8 | (uint8_t)mxf[at + i]; return v; };
                auto tag = [&](size_t set, uint16_t want) -> size_t {   // the value offset of a tag in a local set (4-byte BER)
                    const size_t end = set + 20 + be(set + 17, 3);
                    for (size_t q = set + 20; q + 4 <= end; q += 4 + be(q + 2, 2))
                        if (be(q, 2) == want) return q + 4;
                    return 0;
                };
                const size_t essence = 0x4000 + 16 + 4 + be(0x4000 + 17, 3);   // after the body partition pack
                const size_t idx = mxf.find(idxKey), entries = tag(idx, 0x3f0a);
                assert(idx != std::string::npos && entries && be(entries, 4) == 3 && be(entries + 4, 4) == 11);
                for (int k = 0; k < 3; ++k)
                    assert(mxf.compare(essence + be(entries + 8 + k * 11 + 3, 8), 16, jkey) == 0);
                const size_t desc = mxf.find(rgbaKey), dur = tag(desc, 0x3002);
                assert(desc != std::string::npos && dur && be(dur, 8) == 3);
            }
            // the XML: the CPL names both track files and their durations; the PKL's sizes are the files'
            const std::string cpl = slurp(cplFile), pkl = slurp(pklFile), am = slurp(pkg + "/ASSETMAP.xml");
            assert(cpl.find(imf ? "http://www.smpte-ra.org/schemas/2067-3/2016" : "http://www.smpte-ra.org/schemas/429-7/2006/CPL") != std::string::npos);
            assert(cpl.find(imf ? "<IntrinsicDuration>6000</IntrinsicDuration>" : "<IntrinsicDuration>3</IntrinsicDuration>") != std::string::npos);
            if (imf) assert(cpl.find("<r0:RGBADescriptor") != std::string::npos && cpl.find("<r0:WAVEPCMDescriptor") != std::string::npos &&
                            cpl.find("http://www.smpte-ra.org/ns/2067-21/2020") != std::string::npos);
            else assert(cpl.find("<ScreenAspectRatio>1998 1080</ScreenAspectRatio>") != std::string::npos && cpl.find("<MainSound>") != std::string::npos);
            int listed = 0;
            for (size_t at = pkl.find("<Asset>"); at != std::string::npos; at = pkl.find("<Asset>", at + 1))
            {
                const std::string file = between(pkl, "<OriginalFileName>", "</OriginalFileName>", at);
                const long long size = std::stoll(between(pkl, "<Size>", "</Size>", at));
                assert((long long)std::filesystem::file_size(pkg + "/" + file) == size && am.find("<Path>" + file + "</Path>") != std::string::npos);
                ++listed;
            }
            assert(listed == 3 && am.find("<PackingList>true</PackingList>") != std::string::npos);
            std::printf("  %s: %s + %s + CPL + PKL + ASSETMAP — 3 frames read back, every size in the PKL true\n", imf ? "IMF" : "DCP",
                        std::filesystem::path(picFile).filename().c_str(), std::filesystem::path(sndFile).filename().c_str());
        }
        std::printf("  [PASS] packages: a SMPTE DCP (2K Flat, 5.1) and an IMF App 2E (RGB 12-bit, stereo) that read back\n");
    }
    // ── R-MEDIA-1: a CinemaDNG sequence by its pattern, through LibRaw; a vendor RAW refused by name ──
    {
        const std::string first = argv[1];
        const std::string base = first.find('/') == std::string::npos ? std::string(".") : first.substr(0, first.rfind('/'));
        const std::string dir = base + "/A001_C002";
        std::filesystem::create_directories(dir);
        const int w = 64, h = 36;
        for (int k = 0; k < 12; ++k)
        {
            if (k == 5) continue;   // a dropped frame on the card: number 000105 is missing
            std::vector<uint16_t> px((size_t)w * h * 3);
            for (int y = 0; y < h; ++y)
                for (int x = 0; x < w; ++x)
                {
                    const size_t i = ((size_t)y * w + x) * 3;
                    px[i] = (uint16_t)(x * 300 + k * 1500);   // brighter frame by frame
                    px[i + 1] = 12000;
                    px[i + 2] = (uint16_t)(y * 400 + 100);
                }
            char name[64];
            std::snprintf(name, sizeof name, "/A001_C002_%06d.dng", 100 + k);
            assert(dngtest::write(dir + name, w, h, px, 25.0, {0x00, 0x10, 0x00, 0x01, 0, 0, 0, 0}));   // 01:00:10:00
        }
        std::string pattern, why;
        assert(interstellar::seq::fromFolder(dir, pattern, why) && pattern == dir + "/A001_C002_%06d.dng");
        assert(interstellar::looksLikeVideo(pattern) && interstellar::seq::stem(pattern) == "A001_C002");
#ifdef INTERSTELLAR_HAVE_LIBRAW
        interstellar_host::HostFrameSource src;
        interstellar::IFrameSource::Info info;
        assert(src.open(pattern, info));
        std::printf("  CinemaDNG %s: %dx%d %.2f fps, %lld frames, %d-bit, TC %s, reel %s\n", pattern.c_str(), info.width, info.height,
                    info.fps, info.frames, info.bitDepth, info.timecode.c_str(), info.reel.c_str());
        assert(info.width == w && info.height == h && info.frames == 12 && std::fabs(info.fps - 25.0) < 1e-6);
        assert(info.bitDepth == 16 && info.timecode == "01:00:10:00" && info.reel == "A001_C002");
        interstellar::Raster f0, f3, f4, f5, f6, d2, s2;
        assert(src.frameAt(0, f0) && src.frameAt(3, f3) && src.frameAt(4, f4) && src.frameAt(5, f5) && src.frameAt(6, f6));
        const size_t at = ((size_t)10 * w + 20) * 4;
        std::printf("  frame 0 R %d G %d, frame 3 R %d G %d; frames 4 / 5 (dropped) / 6 R %d %d %d\n", f0.rgba[at], f0.rgba[at + 1],
                    f3.rgba[at], f3.rgba[at + 1], f4.rgba[at], f5.rgba[at], f6.rgba[at]);
        assert(f3.rgba[at] > f0.rgba[at] + 10);
        // one exposure for the clip: the same recorded value develops alike in every frame (green is constant)
        assert(std::abs((int)f3.rgba[at + 1] - (int)f0.rgba[at + 1]) <= 1);
        // the dropped frame holds the one before it — which is its own picture, not the one after
        assert(hashRaster(f5) == hashRaster(f4) && f4.rgba[at] > f3.rgba[at] && f6.rgba[at] > f4.rgba[at]);
        interstellar::Raster f10, f11;
        assert(src.frameAt(10, f10) && src.frameAt(11, f11) && hashRaster(f10) != hashRaster(f11));   // frame k is number first + k
        // deep: the developed 16 bits, not 8 widened — and the 8-bit frame is the deep one rounded
        assert(src.frameAtDeep(2, d2) && d2.deep() && src.frameAt(2, s2));
        size_t fine = 0;
        for (size_t i = 0; i < d2.rgba16.size(); i += 4) fine += d2.rgba16[i] % 257 != 0;
        interstellar::Raster round;
        interstellar::toShallow(d2, round);
        assert(fine > d2.rgba16.size() / 8 && round.rgba == s2.rgba);
        // Cosmo's decoder seam develops the same frame (the reference frame Grade shows)
        interstellar_host::VideoFrameDecoder dec;
        const cosmo::DecodedImage di = dec.decodeFile(pattern + "#t=0.120");   // 0.12 s at 25 fps = frame 3
        assert(di.width == w && di.rgba == f3.rgba && di.name == "A001_C002");
        std::printf("  [PASS] CinemaDNG: pattern from the folder, rate and timecode from its tags, 16-bit, a dropped frame held, Cosmo's seam agrees\n");
#else
        std::printf("  [SKIP] CinemaDNG: this build has no LibRaw\n");
#endif
        // R-MEDIA-3: the decoder seam decodes a stored path from where the .isp says its file is now
        {
            auto sel = std::make_shared<interstellar::FrameSelector>();
            sel->setFile("/gone/plain.mp4#t=0.500", first);
            interstellar_host::VideoFrameDecoder moved(sel);
            const cosmo::DecodedImage di = moved.decodeFile("/gone/plain.mp4#t=0.500");
            interstellar_host::VideoFrameDecoder plain;
            assert(di.width > 0 && plain.decodeFile("/gone/plain.mp4#t=0.500").width == 0);
            std::printf("  [PASS] a relinked path decodes from its new file (%dx%d); unmapped, it is missing\n", di.width, di.height);
        }
        // the vendor formats: refused by name until an SDK build registers a decoder
        std::string need;
        assert(!interstellar_host::makeVideoSource(base + "/clip.R3D", &need) && need.find("RED R3D SDK") != std::string::npos);
        assert(!interstellar_host::makeVideoSource(base + "/clip.braw", &need) && need.find("Blackmagic RAW SDK") != std::string::npos);
        assert(!interstellar_host::vendorDecoderInstalled("r3d"));
        interstellar_host::registerVendorDecoder("r3d", [] { return std::unique_ptr<interstellar::IFrameSource>(new interstellar_host::FrameSourceFFmpeg()); });
        assert(interstellar_host::vendorDecoderInstalled("R3D") && interstellar_host::makeVideoSource(base + "/clip.r3d"));
        std::printf("  [PASS] vendor RAW: %s — and a registered decoder is used\n", need.c_str());
    }
    std::printf("interstellar_host_tests: %d file(s) passed\n", argc - 1);
    return 0;
}
