/*
 *  Cosmo by arstro — cosmo_web_tokens: the web UI's design tokens, printed FROM Theme.h (R-NTWB-9).
 *
 *  The browser front end must look like the window (R-NTWB-5), and the first thing that makes
 *  two UIs look different is two palettes. Typing Theme.h's values into a stylesheet would be
 *  a second, hand-kept copy - the forked-token-file failure arstro.design.rule §2 names ("a
 *  divergence with a delay fuse"). So the stylesheet's tokens are GENERATED: this program calls
 *  the same inline token functions every widget calls and prints them as CSS custom
 *  properties. apps/cosmo/web/css/tokens.css is its committed output; ctest
 *  `cosmo_web_tokens_current` fails when Theme.h changes and the file was not regenerated:
 *
 *      cmake-build/apps/cosmo/cosmo_web_tokens > apps/cosmo/web/css/tokens.css
 *
 *  Only what Theme.h defines is here; motion durations are literals in the widgets (cosmo does
 *  not use Artboard's motion tokens yet, arstro.design.rule §2.5), so base.css carries those
 *  with a citation per value.
 */
#include "Theme.h"
#include <cmath>
#include <cstdio>

using namespace arstro::cosmo_v2;
using artboard::Color;

namespace
{
    int byte(double v) { return (int)std::lround(std::fmax(0.0, std::fmin(1.0, v)) * 255.0); }

    void colour(const char *name, const Color &c)
    {
        if (c.a >= 0.9995)
            std::printf("  --%s: #%02X%02X%02X;\n", name, byte(c.r), byte(c.g), byte(c.b));
        else
            std::printf("  --%s: rgba(%d, %d, %d, %g);\n", name, byte(c.r), byte(c.g), byte(c.b), c.a);
    }

    /** "r, g, b" of an opaque colour, for the parametric tokens (primaryAlpha(a) -> rgba(var(--x-rgb), a)). */
    void rgb(const char *name, const Color &c)
    {
        std::printf("  --%s-rgb: %d, %d, %d;\n", name, byte(c.r), byte(c.g), byte(c.b));
    }
}

int main()
{
    std::printf("/* GENERATED by cosmo_web_tokens from apps/cosmo/Theme.h - do not edit.\n"
                "   Regenerate: cosmo_web_tokens > apps/cosmo/web/css/tokens.css (ctest cosmo_web_tokens_current). */\n"
                ":root {\n");
    // palette:: - theme.css tokens, then the per-surface literals
    colour("background", palette::background());
    colour("foreground", palette::foreground());
    colour("card", palette::card());
    colour("popover", palette::popover());
    colour("primary", palette::primary());
    colour("primary-foreground", palette::primaryForeground());
    colour("secondary", palette::secondary());
    colour("secondary-foreground", palette::secondaryForeground());
    colour("muted", palette::muted());
    colour("muted-foreground", palette::mutedForeground());
    colour("destructive", palette::destructive());
    colour("success", palette::success());
    colour("border", palette::border());
    colour("input", palette::input());
    colour("input-light", palette::inputLight());
    colour("input-light-text", palette::inputLightText());
    colour("switch-background", palette::switchBackground());
    colour("ring", palette::ring());
    colour("canvas-bg", palette::canvasBg());
    colour("histogram-bg", palette::histogramBg());
    colour("left-rail-bg", palette::leftRailBg());
    colour("filmstrip-bg", palette::filmstripBg());
    colour("folder-chip-bg", palette::folderChipBg());
    colour("segmented-bg", palette::segmentedBg());
    colour("curve-plot-bg", palette::curvePlotBg());
    colour("white", palette::white());
    // parametric: whiteAlpha(a), primaryAlpha(a), successAlpha(a), hoverWash(t) = whiteAlpha(0.07 t)
    rgb("white", palette::white());
    rgb("primary", palette::primary());
    rgb("success", palette::success());
    colour("hover-wash", palette::hoverWash(1.0));
    // radius::
    std::printf("  --radius-hairline: %gpx;\n", radius::hairline());
    std::printf("  --radius-control: %gpx;\n", radius::control());
    std::printf("  --radius-pill: %gpx;\n", radius::pill());
    // font:: - the family names the faces are registered under (fonts.css maps them to files)
    std::printf("  --font-sans: \"%s\";\n", font::sans());
    std::printf("  --font-sans-medium: \"%s\";\n", font::sansMedium());
    std::printf("  --font-sans-semibold: \"%s\";\n", font::sansSemiBold());
    std::printf("  --font-mono: \"%s\";\n", font::mono());
    std::printf("  --font-mono-medium: \"%s\";\n", font::monoMedium());
    // metrics::
    std::printf("  --anchor-hit-radius: %gpx;\n", metrics::anchorHitRadius());
    std::printf("}\n");
    return 0;
}
