/*
 *  solaris_web_tokens — the web UI's design tokens, printed FROM Theme.h (R-SVC-7; cosmo's
 *  cosmo_web_tokens, apps/cosmo/cli/webTokens.cpp, for Solaris).
 *
 *  The web face must look like the window, and two hand-kept palettes are the first thing that makes
 *  two faces look different (arstro.design.rule §2: a forked token file is a divergence with a delay
 *  fuse). So the stylesheet's tokens are GENERATED: Solaris's accent is installed exactly as the
 *  window installs it (`installSolarisAccent`, teal), then the same inline token functions every
 *  widget calls — cosmo's palette, Solaris's own surfaces, the track colours, the radii, the faces,
 *  the motion durations — are printed as CSS custom properties. apps/solaris/web/css/tokens.css is the
 *  committed output; ctest `solaris_web_tokens_current` fails when Theme.h moves and it was not
 *  regenerated:
 *
 *      build/apps/solaris/cli/solaris_web_tokens > apps/solaris/web/css/tokens.css
 */
#include "Theme.h"
#include <cmath>
#include <cstdio>

using namespace arstro::solaris_ui;
using artboard::Color;

namespace
{
    int byte(double v) { return (int)std::lround(std::fmax(0.0, std::fmin(1.0, v)) * 255.0); }

    void colour(const char *name, const Color &c)
    {
        if (c.a >= 0.9995)
            std::printf("  --%s: #%02X%02X%02X;\n", name, byte(c.r), byte(c.g), byte(c.b));
        else
            std::printf("  --%s: rgba(%d, %d, %d, %g);\n", name, byte(c.r), byte(c.g), byte(c.b), c.a);
    }

    void rgb(const char *name, const Color &c) { std::printf("  --%s-rgb: %d, %d, %d;\n", name, byte(c.r), byte(c.g), byte(c.b)); }
    void ms(const char *name, double v) { std::printf("  --%s: %gms;\n", name, v); }
}

int main()
{
    installSolarisAccent(); // the window's first call (R-UI-2): every accent-derived token follows it
    std::printf("/* GENERATED by solaris_web_tokens from apps/solaris/app/Theme.h (cosmo's palette, Solaris's teal) - do not edit.\n"
                "   Regenerate: solaris_web_tokens > apps/solaris/web/css/tokens.css (ctest solaris_web_tokens_current). */\n"
                ":root {\n");
    // cosmo's palette, through Solaris's aliases
    colour("background", palette::background());
    colour("foreground", palette::foreground());
    colour("card", palette::card());
    colour("popover", palette::popover());
    colour("primary", palette::primary());
    colour("primary-foreground", palette::primaryForeground());
    colour("secondary", palette::secondary());
    colour("secondary-foreground", palette::secondaryForeground());
    colour("muted", palette::muted());
    colour("muted-foreground", palette::mutedForeground());
    colour("destructive", palette::destructive());
    colour("success", palette::success());
    colour("border", palette::border());
    colour("input", palette::input());
    colour("ring", palette::ring());
    colour("white", palette::white());
    rgb("white", palette::white());
    rgb("primary", palette::primary());
    colour("hover-wash", palette::hoverWash(1.0));
    // Solaris's own surfaces (Theme.h `surface`): the lanes, the ruler, the dock, the meters
    colour("stage-bg", surface::stageBg());
    colour("ruler-bg", surface::rulerBg());
    colour("header-bg", surface::headerBg());
    colour("lane-bg", surface::laneBg());
    colour("lane-alt-bg", surface::laneAltBg());
    colour("deck-bg", surface::deckBg());
    colour("strip-bg", surface::stripBg());
    colour("playhead", surface::playhead());
    colour("meter-low", surface::meterLow());
    colour("meter-mid", surface::meterMid());
    colour("meter-high", surface::meterHigh());
    colour("solo", surface::solo());
    colour("skeleton", surface::skeleton());
    for (int i = 0; i < 10; ++i)
    {
        char name[16];
        std::snprintf(name, sizeof name, "track-%d", i);
        colour(name, surface::track(i));
    }
    // radius:: and the spacing ladder
    std::printf("  --radius-hairline: %gpx;\n", radius::hairline());
    std::printf("  --radius-control: %gpx;\n", radius::control());
    std::printf("  --radius-pill: %gpx;\n", radius::pill());
    std::printf("  --space-pad-x: %gpx;\n", space::padX());
    std::printf("  --space-gap: %gpx;\n", space::gap());
    std::printf("  --space-row-h: %gpx;\n", space::rowH());
    std::printf("  --space-bar-h: %gpx;\n", space::barH());
    // font:: — the family names (base.css maps them to the files `ntwb install` ships)
    std::printf("  --font-sans: \"%s\";\n", font::sans());
    std::printf("  --font-sans-medium: \"%s\";\n", font::sansMedium());
    std::printf("  --font-sans-semibold: \"%s\";\n", font::sansSemiBold());
    std::printf("  --font-mono: \"%s\";\n", font::mono());
    std::printf("  --font-mono-medium: \"%s\";\n", font::monoMedium());
    // motion:: — the durations the window eases with (design rule §2.5)
    ms("motion-hover", motion::kHoverMs);
    ms("motion-cross-fade", motion::kCrossFadeMs);
    ms("motion-select", motion::kSelectMs);
    ms("motion-slide", motion::kSlideMs);
    ms("motion-catch-up", motion::kCatchUpMs);
    ms("motion-reflow", motion::kReflowMs);
    ms("motion-toast-in", motion::kToastInMs);
    ms("motion-toast-out", motion::kToastOutMs);
    ms("motion-meter-fall", motion::kMeterFallMs);
    std::printf("}\n");
    return 0;
}
