#include "ApiDoc.h"
#include "AppModelCodec.h"
#include "Command.h"
#include "Event.h"
#include "Json.h"
#include "ParamRegistry.h"

namespace arstro
{
namespace interstellar
{
    namespace
    {
        const char *kApiVersion = "1";

        std::string range(const ParamDef &d)
        {
            if (d.kind != ParamKind::Scalar && d.kind != ParamKind::Int) return std::string();
            if (d.min == 0 && d.max == 0) return std::string();
            return canonicalNumber(d.min) + ".." + canonicalNumber(d.max);
        }

        std::string mdCell(const std::string &s)
        {
            std::string o;
            for (char c : s) o += c == '|' ? std::string("\\|") : std::string(1, c);
            return o;
        }
    }

    std::string apiJson()
    {
        Json root = Json::object();
        root.set("app", "interstellar");
        root.set("apiVersion", kApiVersion);
        root.set("about",
                 "A video colour tool that can cut. Drive it with one command per line (the grammar below), "
                 "observe it through `state print --json` (the model below) and the event stream, address any "
                 "value with `set`/`get`/`eval`. Generated by `interstellar-cc api --json`; do not edit.");

        Json cmds = Json::array();
        for (const auto &s : commandSpecs())
        {
            Json flags = Json::array();
            for (const auto &f : s.flags)
            {
                const auto eq = f.find('=');
                Json fl = Json::object();
                fl.set("name", eq == std::string::npos ? f : f.substr(0, eq));
                fl.set("value", eq == std::string::npos ? std::string() : f.substr(eq + 1));
                flags.push(fl);
            }
            cmds.push(Json::object()
                          .set("verb", s.verb)
                          .set("usage", usageOf(s))
                          .set("args", s.args)
                          .set("minArgs", s.minArgs)
                          .set("maxArgs", s.maxArgs)
                          .set("flags", flags)
                          .set("summary", s.summary)
                          .set("requirement", s.requirement));
        }
        root.set("commands", cmds);

        Json evs = Json::array();
        for (const auto &e : eventSpecs())
        {
            Json f = Json::array();
            for (const auto &k : e.fields) f.push(Json::string(k));
            evs.push(Json::object().set("name", e.name).set("fields", f).set("summary", e.summary));
        }
        root.set("events", evs);

        Json model = Json::array();
        for (const auto &f : appModelFields())
            model.push(Json::object()
                           .set("path", f.path)
                           .set("type", f.type)
                           .set("stable", !f.machineDependent)
                           .set("doc", f.doc));
        root.set("model", model);

        Json addrs = Json::array();
        for (const auto &d : paramDefs())
        {
            Json a = Json::object();
            a.set("address", d.pattern);
            a.set("owner", ownerName(d.owner));
            a.set("key", d.key);
            a.set("kind", kindName(d.kind));
            a.set("unit", d.unit);
            a.set("range", range(d));
            if (d.kind == ParamKind::Scalar || d.kind == ParamKind::Int || d.kind == ParamKind::Bool)
                a.set("neutral", Json::number(d.neutral));
            a.set("doc", d.doc);
            addrs.push(a);
        }
        root.set("addresses", addrs);
        return root.dump();
    }

    std::string apiMarkdown()
    {
        std::string md;
        md += "# Interstellar API\n\n";
        md += "> **Generated** by `interstellar-cc api --md` from the tables the parser, the event stream, the model "
              "codec and the address router run on. Do not edit: `ctest -R interstellar_api_current` fails when this "
              "file and the code disagree (R-API-1). Machine-readable twin: [`api.json`](api.json).\n\n";
        md += "**How an agent drives Interstellar** (R-API-2): *discover* with `api --json`; *reach* with one command "
              "line; *observe* through `state print --json --stable` or the `[evt]` stream; *assert* with `eval`.\n\n";
        md += "```\n"
              "interstellar-cc --script cut.txt          # one command per line, `#` comments\n"
              "interstellar-cc project open mv.isp : set s_day01.basic.exposure=0.35 : project save\n"
              "```\n\n";

        md += "## Commands\n\n| usage | does | req |\n|---|---|---|\n";
        for (const auto &s : commandSpecs())
            md += "| `" + mdCell(usageOf(s)) + "` | " + mdCell(s.summary) + " | " + s.requirement + " |\n";

        md += "\n## Addresses\n\n"
              "`set <address>=<value>` routes by owner. A **cosmo** address writes THROUGH to the hosted Cosmo project "
              "when the current timeline is a root, and becomes the current version's override (`#tlgrade`) when it "
              "is derived — a scalar override is ADDED to the rack's value, so a later base edit still arrives; a "
              "list or wheel override replaces it. A pinned version refuses colour writes, naming the pin. A **clip** "
              "write on a derived version becomes a `#tlset`. `revert <address>` drops an override.\n\n"
              "| address | owner | kind | unit | range | neutral | meaning |\n|---|---|---|---|---|---|---|\n";
        for (const auto &d : paramDefs())
        {
            const bool num = d.kind == ParamKind::Scalar || d.kind == ParamKind::Int || d.kind == ParamKind::Bool;
            md += "| `" + mdCell(d.pattern) + "` | " + ownerName(d.owner) + " | " + kindName(d.kind) + " | " +
                  mdCell(d.unit) + " | " + range(d) + " | " + (num ? canonicalNumber(d.neutral) : std::string()) +
                  " | " + mdCell(d.doc) + " |\n";
        }

        md += "\n## Events\n\nEach line on the stream is `[evt] <name> key=value …`.\n\n"
              "| event | fields | meaning |\n|---|---|---|\n";
        for (const auto &e : eventSpecs())
        {
            std::string f;
            for (size_t i = 0; i < e.fields.size(); ++i) f += (i ? ", " : "") + std::string("`") + e.fields[i] + "`";
            md += "| `" + e.name + "` | " + f + " | " + mdCell(e.summary) + " |\n";
        }

        md += "\n## Model\n\n`state print --json` prints these keys in this order. `--stable` omits the rows marked "
              "*machine* and reduces paths to file names, so two front ends showing the same state print the same "
              "text.\n\n| path | type | | meaning |\n|---|---|---|---|\n";
        for (const auto &f : appModelFields())
            md += "| `" + f.path + "` | " + mdCell(f.type) + " | " + (f.machineDependent ? "*machine*" : "") + " | " +
                  mdCell(f.doc) + " |\n";
        return md;
    }
}
}
