#!/usr/bin/env python3
"""Writes song.txt — Pachelbel's Canon in D (public domain) as a 128 bpm EDM track, for `solaris-cc --script`.
The script is the song; this only spells its notes (R-SVC-9). Ids are those a new song hands out in order;
the `made:` lines of the run confirm them."""
import sys
L = []
def c(line=""): L.append(line)

# The ground: a chord every 2 beats, 8 chords = 16 beats (4 bars)
CH = [("D", "D2"), ("A", "A1"), ("Bm", "B1"), ("F#m", "F#1"), ("G", "G1"), ("D", "D2"), ("G", "G1"), ("A", "A1")]
TONES = {"D": ["D4", "F#4", "A4", "D5"], "A": ["A3", "C#4", "E4", "A4"], "Bm": ["B3", "D4", "F#4", "B4"],
         "F#m": ["F#3", "A3", "C#4", "F#4"], "G": ["G3", "B3", "D4", "G4"]}
def notes(seq): return '"' + " ".join(seq) + '"'

c("# Canon in D (Johann Pachelbel, c. 1680 — public domain), arranged as EDM for Solaris by an agent")
c("project new canon.slp --bpm 128 --name \"Canon in D\"")
c()
c("# — the kick: its own strip, so it can key the sidechains (ch_2, dv_1, pt_1, ln_1)")
c("clip add --instrument drums --at 32 --length 32")
c("set ch_2.name=Kick dv_1.kick.tune=-2 dv_1.kick.decay=380 dv_1.kick.tone=0.35")
c('pattern steps pt_1 --pitch kick "x...x...x...x..."')
c("clip add --strip ch_2 --pattern pt_1 --at 80 --length 32")
c()
c("# — the rest of the kit (ch_3, dv_2): hats in the intro, the groove, a clap roll in the build")
c("clip add --instrument drums --at 16 --length 16")
c("set ch_3.name=Drums dv_2.clap.level=-2 dv_2.chat.level=-3 dv_2.ohat.level=-7 dv_2.chat.pan=0.3 dv_2.ohat.pan=-0.3 dv_2.chat.tone=0.75")
c('pattern steps pt_2 --pitch closed-hat "..x...x...x...x." --vel 80')
c("pattern duplicate pt_2 --name Groove")
c('pattern steps pt_3 --pitch clap "....x.......x..."')
c('pattern steps pt_3 --pitch closed-hat "x.x.x.x.x.x.x.x." --vel 70')
c('pattern steps pt_3 --pitch open-hat "..x...x...x...x." --vel 60')
c("clip add --strip ch_3 --pattern pt_3 --at 32 --length 32")
c("clip add --strip ch_3 --pattern pt_3 --at 80 --length 32")
c("pattern new --name Roll --length 16")
roll = "x...x...x...x...x...x...x...x...x.x.x.x.x.x.x.x.xxxxxxxxxxxxxxxx"
c(f'pattern steps pt_4 --pitch clap "{roll}" --vel 90')
c("clip add --strip ch_3 --pattern pt_4 --at 64 --length 16")
c()
c("# — the bass (ch_4, dv_3): the ground on the off-beats")
c("clip add --instrument synth --at 32 --length 32")
c("set ch_4.name=Bass pt_5.length=16")
c("set dv_3.osc1.wave=saw dv_3.osc2.wave=sine dv_3.osc2.octave=-1 dv_3.osc2.level=0.7 dv_3.filter.cutoff=650 dv_3.filter.res=0.2 dv_3.filter.env=1.5 dv_3.amp.decay=160 dv_3.amp.sustain=0.6 dv_3.amp.release=90 dv_3.volume=-8")
bass = []
for i, (_, root) in enumerate(CH):
    for k in range(2): bass.append(f"{root}@{i*2+k+0.5}:0.42")
c(f"notes add pt_5 {notes(bass)} --vel 112")
c("clip add --strip ch_4 --pattern pt_5 --at 80 --length 32")
c()
c("# — the pad (ch_5, dv_4): the chords all the way, a wide supersaw")
c("clip add --instrument synth --at 0 --length 128")
c("set ch_5.name=Pad pt_6.length=16")
c("set dv_4.osc1.voices=5 dv_4.osc1.detune=32 dv_4.osc1.level=0.6 dv_4.osc2.wave=saw dv_4.osc2.octave=0 dv_4.osc2.voices=5 dv_4.osc2.detune=22 dv_4.osc2.level=0.5 dv_4.filter.res=0.15 dv_4.filter.env=0.5 dv_4.amp.attack=220 dv_4.amp.decay=600 dv_4.amp.sustain=0.85 dv_4.amp.release=700 dv_4.volume=-16")
for i, (ch, _) in enumerate(CH):
    oc = 4 if ch in ("D", "Bm") else 3
    inv = 0 if ch in ("D", "Bm") else 1
    c(f"note add pt_6 --chord {ch} --at {i*2} --length 2 --vel 80 --octave {oc} --inversion {inv}")
c()
c("# — the canon itself (ch_6, dv_5): a pluck — line A, line B, then the eighth-note variation")
c("clip add --instrument synth --at 16 --length 16")
c("set ch_6.name=Canon pt_7.length=16")
c("set dv_5.osc1.voices=3 dv_5.osc1.detune=16 dv_5.osc2.wave=square dv_5.osc2.octave=0 dv_5.osc2.level=0.35 dv_5.filter.cutoff=900 dv_5.filter.res=0.3 dv_5.filter.env=3.5 dv_5.fenv.attack=1 dv_5.fenv.decay=240 dv_5.fenv.sustain=0.15 dv_5.amp.decay=450 dv_5.amp.sustain=0.45 dv_5.amp.release=260 dv_5.volume=-10")
A = ["F#5", "E5", "D5", "C#5", "B4", "A4", "B4", "C#5"]
B = ["D5", "C#5", "B4", "A4", "G4", "F#4", "G4", "E4"]
C = ["D5", "F#5", "A5", "G5", "F#5", "D5", "F#5", "E5", "D5", "B4", "D5", "A4", "G4", "B4", "A4", "G4"]
c(f"notes add pt_7 {notes(f'{p}@{i*2}:1.9' for i, p in enumerate(A))} --vel 96")
c("pattern new --name \"Canon B\" --length 16")
c(f"notes add pt_8 {notes(f'{p}@{i*2}:1.9' for i, p in enumerate(B))} --vel 96")
c("pattern new --name \"Canon C\" --length 16")
c(f"notes add pt_9 {notes(f'{p}@{i}:0.9' for i, p in enumerate(C))} --vel 104")
c("clip add --strip ch_6 --pattern pt_7 --at 32 --length 16")
c("clip add --strip ch_6 --pattern pt_8 --at 48 --length 16")
c("clip add --strip ch_6 --pattern pt_9 --at 64 --length 16")
c("clip add --strip ch_6 --pattern pt_9 --at 80 --length 32")
c("clip add --strip ch_6 --pattern pt_7 --at 112 --length 16")
c()
c("# — an arpeggio for the drop (ch_7, dv_6): each chord's tones in sixteenths")
c("clip add --instrument synth --at 80 --length 32")
c("set ch_7.name=Arp pt_10.length=16")
c("set dv_6.osc1.wave=square dv_6.osc1.level=0.7 dv_6.osc2.level=0 dv_6.filter.cutoff=1400 dv_6.filter.env=3 dv_6.fenv.decay=110 dv_6.fenv.sustain=0 dv_6.amp.decay=150 dv_6.amp.sustain=0 dv_6.amp.release=90 dv_6.volume=-14")
arp = []
for i, (ch, _) in enumerate(CH):
    t = TONES[ch]; seq = [t[0], t[1], t[2], t[3], t[2], t[1], t[2], t[3]]
    for k, p in enumerate(seq): arp.append(f"{p}@{i*2 + k*0.25}:0.2")
c(f"notes add pt_10 {notes(arp)} --vel 90")
c()
c("# — space: a reverb and a tempo-synced delay (a dotted eighth, by formula)")
c("strip add --kind bus --name Reverb")
c("device add ch_8 --type reverb")
c("set dv_7.decay=2600 dv_7.mix=1 dv_7.lowcut=250")
c("strip add --kind bus --name Delay")
c("device add ch_9 --type delay")
c("set dv_8.time=\"=60000/bpm*0.75\" dv_8.feedback=0.35 dv_8.mix=1 dv_8.tone=3500")
c("send add ch_6 --to ch_8 --gain -8")
c("send add ch_6 --to ch_9 --gain -14")
c("send add ch_5 --to ch_8 --gain -12")
c("send add ch_7 --to ch_9 --gain -16")
c("send add ch_3 --to ch_8 --gain -20")
c()
c("# — the pump: the kick keys a compressor on the bass and on the pad")
c("device add ch_4 --type compressor")
c("set dv_9.sidechain=on dv_9.threshold=-30 dv_9.ratio=6 dv_9.attack=1 dv_9.release=140")
c("device add ch_5 --type compressor")
c("set dv_10.sidechain=on dv_10.threshold=-30 dv_10.ratio=4 dv_10.attack=2 dv_10.release=180")
c("send add ch_2 --to ch_4 --sidechain")
c("send add ch_2 --to ch_5 --sidechain")
c()
c("# — the pad's filter opens through the intro, closes, rises through the build (bezier), opens on the drop")
c("auto create dv_4.filter.cutoff")
c("auto point move au_1 --at 0 --value 300")
c("auto point add au_1 --at 31 --value 4200 --shape bezier")
c("auto point shape au_1 --at 31 --speed-in 220 --influence-in 60 --speed-out 0 --influence-out 33")
c("auto point add au_1 --at 64 --value 900")
c("auto point add au_1 --at 79.5 --value 9000 --shape bezier")
c("auto point shape au_1 --at 79.5 --speed-in 1600 --influence-in 75 --speed-out 0 --influence-out 33")
c("auto point add au_1 --at 80 --value 5200 --shape hold")
c("auto point add au_1 --at 112 --value 5200")
c("auto point add au_1 --at 128 --value 350")
c()
c("# — width: a chorus on the pad, the arp a little to the right")
c("device add ch_5 --type chorus")
c("set dv_11.rate=0.4 dv_11.depth=5 dv_11.delay=14 dv_11.mix=0.45 ch_7.pan=0.3")
c()
c("# — the mix, and the master")
c("set ch_2.gain=-3 ch_3.gain=-6 ch_4.gain=-5 ch_5.gain=-6 ch_6.gain=-4 ch_7.gain=-8 ch_8.gain=-6 ch_9.gain=-9")
c("device add master --type limiter")
c("set dv_12.gain=5 dv_12.ceiling=-0.8")
c()
c("ls")
c("audit")
c("project save")
c("render --out canon.wav --stems ch_2,ch_4,ch_5,ch_6")
open(sys.argv[1] if len(sys.argv) > 1 else "song.txt", "w").write("\n".join(L) + "\n")
